### ISSUE TITLE
Test on other providers than AWS

### ISSUE THREAD

**Issue by erez-rabih** [nanit/kubernetes-graphite-cluster#6]
Currently the setup has only been tested on AWS.
It would be nice to have it tested and adjusted to other k8s configurations as well.

**Comment by jakoguta** [comment]
I installed this in GKE and it works fine.

**Comment by erez-rabih** [comment]
@jakoguta Thanks for your update on GKE.

Regarding graphing Web UI: You can use the default Grafana UI which ships with Kubernetes. All you need to do is add a Graphite source on http://graphite:80.

**Comment by jakoguta** [comment]
Unfortunately, in GKE Grafana UI does not come by default. Looking for a work around...

**Comment by erez-rabih** [comment]
@jakoguta You can just use the [Grafana default image](https://github.com/grafana/grafana-docker), and add the Graphite backend to it.

You can also use the Kubernetes Grafana manifest file located [here](https://github.com/kubernetes/kubernetes/tree/v1.6.3/cluster/addons/cluster-monitoring/influxdb) to deploy.

**Comment by jakoguta** [comment]
@erez-rabih Thanks very much. I decided to use the Grafana default image and it works fine.
